/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "user.index": [],
    "user.store": [],
    "user.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.get-role": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "password.confirm": [],
    "logout": [],
    "register.index": [],
    "register.store": [],
    "register.update": [
        {
            "name": "register",
            "required": true,
            "binding": "id"
        }
    ],
    "register.destroy": [
        {
            "name": "register",
            "required": true,
            "binding": "id"
        }
    ],
    "register.reveal-password": [
        {
            "name": "register",
            "required": true,
            "binding": "id"
        }
    ],
    "register.check-can-update": [
        {
            "name": "register",
            "required": true,
            "binding": "id"
        }
    ],
    "register.get-changes": [
        {
            "name": "register",
            "required": true,
            "binding": "id"
        }
    ],
    "logs.index": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
